# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
      include:
        - main
      exclude:
        - dev
        - staging
        - master
pr: none

resources:
- repo: self

variables:
  tag: latest
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'artsdatabanken/clavis-routing'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: Docker@2
      displayName: Publish image
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'artsdatabanken/clavis-routing'
        command: 'push'
        tags: '$(tag)'
    - task: AzureAppServiceManage@0
      inputs:
        azureSubscription: 'prod-deploy-code'
        Action: 'Restart Azure App Service'
        WebAppName: 'adb-prod-clavis-as'